### ISSUE TITLE
Project child paths are made absolute when saved

### ISSUE THREAD

**Issue by ladislavlencucha** [jshiell/checkstyle-idea#569]
It seems that starting from 5.66.0 the checkstyle-idea.xml file is changed and all references to $PROJECT_DIR$ are replaced by the actual path. This causes problems, because we have checkstyle-idea.xml in git and every developer has the project checked out elsewhere. Also active-configuration is being saved as active-configuration-0

Example of file being saved before:
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="LOCAL_FILE:$PROJECT_DIR$/etc/codestyle/checkstyle.xml:pm1" />
        <entry key="checkstyle-version" value="8.45.1" />
        <entry key="copy-libs" value="false" />
        <entry key="location-0" value="BUNDLED:(bundled):Sun Checks" />
        <entry key="location-1" value="BUNDLED:(bundled):Google Checks" />
        <entry key="location-2" value="LOCAL_FILE:$PROJECT_DIR$/etc/codestyle/checkstyle.xml:pm1" />
        <entry key="scan-before-checkin" value="true" />
        <entry key="scanscope" value="JavaOnlyWithTests" />
        <entry key="suppress-errors" value="false" />
      </map>
    </option>
  </component>
</project>

```

Example of file being saved now:
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration-0" value="LOCAL_FILE:C:/projects/example-project/etc/codestyle/checkstyle.xml:example" />
        <entry key="checkstyle-version" value="8.45.1" />
        <entry key="copy-libs" value="false" />
        <entry key="location-0" value="BUNDLED:(bundled):Sun Checks;All" />
        <entry key="location-1" value="BUNDLED:(bundled):Google Checks;All" />
        <entry key="location-2" value="LOCAL_FILE:C:/projects/example-project/etc/codestyle/checkstyle.xml:example;All" />
        <entry key="scan-before-checkin" value="true" />
        <entry key="scanscope" value="JavaOnlyWithTests" />
        <entry key="suppress-errors" value="false" />
      </map>
    </option>
  </component>
</project>

```

**Comment by jshiell** [comment]
Hmm, I'll have a look, but the $PROJECT_DIR$ substitution is primarily IDEA rather than us.

The `active-configuration-0` _is_ intentional, however, now we support multiple active files.

**Comment by ladislavlencucha** [comment]
Yeah, it's strange, because it does not happen to everybody, only to some of the Windows users and only after upgrade of IDEA to latest altogether with checkstyle plugin.

However, the issue has not happened yet on Linux

**Comment by LennyKarpel** [comment]
I and my co-workers are seeing $PROJECT_DIR$ being replaced by the actual path as well. MacOS. IntelliJ IntelliJ IDEA 

2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 11, 2022
CheckStyle-IDEA (5.66.0)

**Comment by ladislavlencucha** [comment]
I tried with 2022.1.1, same problem, tried 2021.3, same problem.

I reverted the plugin to 0.63 and the issue has not yet occured.

**Comment by jshiell** [comment]
Mostly bad news so far. It seems, based on the above, that it affects Linux, Windows, and Mac OS - which is handy, as I develop on Mac OS. It also means it probably isn't tied to the differences between *nix and Windows FSs. Unfortunatley, I can't reproduce it. I've tried adding, deleting, adding entries outside of the path - nothing has seemed to stop the tokenisation working correctly for me.

```
<entry key="active-configuration-0" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/working-checkstyle-rules-8.24.xml:Working;All" />
<entry key="checkstyle-version" value="10.2" />
<entry key="copy-libs" value="false" />
<entry key="location-0" value="BUNDLED:(bundled):Sun Checks;All" />
<entry key="location-1" value="BUNDLED:(bundled):Google Checks;All" />
<entry key="location-10" value="LOCAL_FILE:/Users/jsh/Downloads/working-checkstyle-rules-8.24.xml:WorkingOutsideProject;All" />
<entry key="location-11" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/working-checkstyle-rules-8.24.xml:aasasd;Tests" />
<entry key="location-12" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/working-checkstyle-rules-8.24.xml:anothertest;Production" />
<entry key="location-2" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/issue-545.xml:545;All" />
<entry key="location-3" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/working-checkstyle-rules-8.24.xml:Check3;All" />
<entry key="location-4" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/issue-485.xml:Issue 485;All" />
<entry key="location-5" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/issue-550.xml:Issue 550;All" />
<entry key="location-6" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/issue-545.xml:Test scope test;All" />
<entry key="location-7" value="HTTP_URL:http://demo:demo@localhost:8000/working-checkstyle-rules-8.24.xml:Working BA test;All" />
<entry key="location-8" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/working-checkstyle-rules-8.24.xml:Working;All" />
<entry key="location-9" value="LOCAL_FILE:$PROJECT_DIR$/test-configs/working-checkstyle-rules-8.24.xml:WorkingInsideProject;All" />
```

It doesn't help that this area is a mess - originally we did this [de]tokenisation ourselves (`PRJ_DIR` in the codebase), but at some point IDEA started doing it magically on saved files, at which point we also switched to `PROJECT_DIR` to match IDEA and make sure we were consistent across IDE versions. While it should be harmless when detokenisation is automatic (and indeed should make it more robust if anything, as it adds a secondary check that items have been serialised/deserialised), I should probably remove our support for detokeisation entirely, but I'm wary of doing so without finding official documentation from Jetbrains - all I've found to date is [forum posts like this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/207470105-How-to-disable-auto-expanding-of-PROJECT-DIR-etc-PathMacro-for-my-plugin-settings-).

> this is how serialization of project configurations works in IntelliJ IDEA, paths are automatically collapsed on save and expanded on load, so you don't need to expands them by hand in your code and user don't need to know macros to make his settings portable between different machines. Even if you use PersistentStateComponent<Element> the paths will be collapsed on save and expanded on load.

My current working theory is this is relating to the project dir madness in newer IDEA SDKs. To quote from the docs:

```
public fun Project.guessProjectDir(): VirtualFile?

Tries to guess the "main project directory" of the project.

There is no strict definition of what is a project directory, since a project can contain multiple modules located in different places, and the .idea directory can be located elsewhere (making the popular Project.getBaseDir method not applicable to get the "project directory"). This method should be preferred, although it can't provide perfect accuracy either.
```

The elephant in the room is - why would this change between 0.63 and now? Reviewing the changes, the active location serialisation has changed to support multiple values, but the location serialisation hasn't been touched - and your example clearly demonstrates it breaking on both. So there's no obvious smoking gun, despite your testing suggesting very strongly that it is tied to this version change.

In any case, first goal is for me to be able to reproduce it. As such, do you have any suggestions on where my environment may differ from yours? I presume you're using a pretty standard project layout, i.e. <project-dir> is the base of the project, and the `.idea` folder file is a child of this (or do you use the older `.ipr`?) with the rest of the project self-contained within this?

**Comment by ladislavlencucha** [comment]
pretty standard layout with where everything is under PROJECT_DIR, including .idea folder. Taking the example from my initial description, everything is under C:/projects/example-project:
C:/projects/example-project/.idea
C:/projects/example-project/pom.xml

I have 3 questions:

1. why would you even attempt to change "active-configuration" to "active-configuration-0"? This seems to imply that "save" operation had been triggered and that whatever happened next persisted resolved path.
2. Wasn't there a change in saving the configuration? Maybe that is the problem somehow?
3. What can I do to help you analyze the problem?

**Comment by LennyKarpel** [comment]
For us it seems to be OK at times .. then 'something' happens and the file is _all of a sudden_ marked changed with the 'issue'. I can not relate the 'change' to something that we do at this point. It certainly does not seem to be tied to making any configuration changes.

**Comment by ladislavlencucha** [comment]
For me, it is something related to commit tool window. When I press ctrl+K, then the commit tool window is restored, modified files ticked and the configuration file is suddenly modified too.

**Comment by LennyKarpel** [comment]
Well .. that is certainly when I _notice_ that the file has been altered .. whether that is causal or not ...  ¯\_(ツ)_/¯

**Comment by jshiell** [comment]
It's hard to tell tbh, but the commit dialogue gives me something to try test, at least - thanks.

All we do is register the serialisation object with IDEA - IDEA then decides when to save it, or not. `active-configuration`->`active-configuration-0` definite implies the bean has been invoked, as the new version did change the format to support multiple active configs. Saving without a change shouldn't be an issue though - you can force a save at any point with cmd-S or equivalent, and I was able to reproduce it that way.

**Comment by Gabri3lZ** [comment]
I had to remove my configuration file and re-add it with the option "Store relative to project location". This seems to fix the issue for me.

![image](https://user-images.githubusercontent.com/4402542/168054787-0f1c7e24-503d-4abe-b3dd-03b37b625256.png)

**Comment by LennyKarpel** [comment]
Interesting. That changes the config file line to:

`<entry key="active-configuration-0" value="PROJECT_RELATIVE:$PROJECT_DIR$/config/checkstyle/checkstyle.xml:Sheets2 Checks;All" />
`

using PROJECT_RELATIVE rather than LOCAL_FILE. In either case it does say PROJECT_DIR .. but maybe that makes no difference _anymore_.

**Comment by LennyKarpel** [comment]
So .. sad to say .. even with that change (PROJECT_RELATIVE rather than LOCAL_FILE) .. the issue is still happening to me .. replacing PROJECT_DIR with the full path. Sorry.

**Comment by ladislavlencucha** [comment]
@Gabri3lZ thanks! this seems to have fixed the issue for me
@LennyKarpel I had to select the checkbox first, then choose the file, reversed order does not work..

**Comment by LennyKarpel** [comment]
I did what you stated (the order). It seems ok for a while. Then it all of a sudden did this:

**Comment by jshiell** [comment]
I wouldn't _expect_ this to change it, as the tokenisation is magic by IDEA, and it's that part that seems to be intermittently broken.

**Comment by LennyKarpel** [comment]
I certainly agree with the 'intermittent' characterization .. if you 'fix' the file you can work for quite some time .. and then, all of a sudden, the file changes.

**Comment by LennyKarpel** [comment]
Maybe myth and superstition .. but .. I had a set of changed files .. I _shelved_ all of those changes .. then the checkstyle-idea.xml file appeared to have been changed .. I did this many times in a row (removing the changes to the checkstyle file and un-shelving those changes to start the cycle again) .. hope that makes sense and helps.

**Comment by jshiell** [comment]
Still no luck with reproducing. The only thing I can find unusual in what we do is that the file path is only part of the property; hence I wonder if we might be better results if we split that out. It's not a 5m job though, but would offer a chance to fix some other problems with the serialisation (i.e. the items not having an ID for a start).

**Comment by ladislavlencucha** [comment]
It happened to me now too.  It happened when I refactored method name. IDEA 2022.1.1, version of plugin 5.66

So it seems to be connected to some events when code is being changed and the settings are the persisted.

**Comment by jshiell** [comment]
My working theory is that this is due to the extra serialisation information added in the last patch regarding the location scope. As a solution, I'm working on a new serialisation format that'll separate out the fields. It's turning out to be a larger chunk of work than I expected, but I hope to have something to test this weekend.

**Comment by jshiell** [comment]
Sorry for the delay, but I now have a test release with the serialisation changes. Given the potential impact of this problem - and that given I haven't managed to reproduce this I can't guarantee it fixes the problem - I'd appreciate it if people could give this a try and offer feedback 🤞 

[5.66.1 pre-release](https://www.icloud.com/iclouddrive/0d3UrJoyPWbUGhYJI8QBKlHJA#CheckStyle-IDEA-5.66.1.test)

**Comment by LennyKarpel** [comment]
I played some with [5.66.1 pre-release](https://www.icloud.com/iclouddrive/0d3UrJoyPWbUGhYJI8QBKlHJA#CheckStyle-IDEA-5.66.1.test) and so for it seems good for me !! Fingers crossed !!

**Comment by LennyKarpel** [comment]
Saw this tonight w/  [5.66.1 pre-release](https://www.icloud.com/iclouddrive/0d3UrJoyPWbUGhYJI8QBKlHJA#CheckStyle-IDEA-5.66.1.test) --> [exception.txt](https://github.com/jshiell/checkstyle-idea/files/8751210/exception.txt)

**Comment by jshiell** [comment]
Thanks - I'll try and get that sorted tonight.

**Comment by jshiell** [comment]
Hopefully fixed - I've made the deserialisation code more paranoid about IDEA leaving nulls there. God I miss Kotlin.

[CheckStyle-IDEA-5.66.1.test2](https://www.icloud.com/iclouddrive/02crAx4PhLYdOvHF6gTJtSoAw#CheckStyle-IDEA-5.66.1.test2)

**Comment by ladislavlencucha** [comment]
So yesterday I installed RC2 on IDEA 2022.1.2 on Windows and today I am getting error popup:
Unable to save plugin settings
The plugin CheckStyle-IDEA failed to save settings and has been disabled. Please restart IntelliJ IDEA

It happened once I rolled back the modified xml file and then pressed ctrl+S to save another file I was modifying.

**Comment by jshiell** [comment]
@ladislavlencucha was there any exception logged? 

What do you mean by "rolled back the modified XML file" ... the XML format has changed from the released versions, so while it will migrate it on load, IDEA is unlikely to be happy if you change the configuration while it's running.

**Comment by ladislavlencucha** [comment]
1. Exception logged:
No, just a Notification in "Notifications" tool windows
2. Rolled back
Yeah, that was my mistake. I thought that the format stays as it is, so I rolled back, because it is becoming matter of habit lately..
3. I checked the modified file and sadly, it contains absolute path:
<option name="locations">
<list>
<ConfigurationLocation id="8786fc83-e187-44e5-a25c-56ddd57a57d9" type="BUNDLED" scope="All" description="Sun Checks">(bundled)</ConfigurationLocation>
<ConfigurationLocation id="9e21369b-7e23-4481-9f03-a749830b2ca0" type="BUNDLED" scope="All" description="Google Checks">(bundled)</ConfigurationLocation>
<ConfigurationLocation id="e85e46be-d89e-4842-9657-72ed421dee5a" type="PROJECT_RELATIVE" scope="All" description="pm1">C:\projects\myproject1\etc\codestyle\checkstyle.xml</ConfigurationLocation>

**Comment by jshiell** [comment]
I presume your project dir is `c:\projects\myproject1`? If so, you shouldn't need to use project-relative - that's purely there for items outside of the project dir that you want to be referenced relatively. Anything else, IDEA should collapse.

I've found one problem, thanks to your file though - those file paths should be stored as system indepedent (i.e. `c:/projects/myproject1..` in this case), so I'll fix that and upload another version. Joys of not having a Windows box to test on.

**Comment by jshiell** [comment]
[5.66.1 RC3](https://www.icloud.com/iclouddrive/038fYC8hkBKGgaaog06mG4e6Q#CheckStyle-IDEA-5.66.1.rc3) - this should fix the missing normalisation on Windows paths. Whether that'll effect normalisation though, who knows.

**Comment by ladislavlencucha** [comment]
I am still getting the Notification mentioned above. On both Windows and Ubuntu. Anybody else having the same problem?

**Comment by ladislavlencucha** [comment]
All right, so it seems after forced restart of IDEA (basically clear caches), the issue is not present anymore. And so far I can say the file seems to keep relative reference.

**Comment by keturn** [comment]
5.66.1 RC3 seems to fix the absolute path problem for me. (IU-221.5787.30 on Linux)
Glad you tracked it down!

**Comment by jshiell** [comment]
Thanks folks for all your help with tracking this down!

I've released the fix in 5.67.0 🤞

**Comment by ladislavlencucha** [comment]
Hm, now i tried 5.67 and it seems the bundled configuration id got re-generated

What I have in git:
<ConfigurationLocation id="8786fc83-e187-44e5-a25c-56ddd57a57d9" type="BUNDLED" scope="All" description="Sun Checks">(bundled)</ConfigurationLocation>
<ConfigurationLocation id="9e21369b-7e23-4481-9f03-a749830b2ca0" type="BUNDLED" scope="All" description="Google Checks">(bundled)</ConfigurationLocation>

What is now the content of the file (after IDEA restart):
<ConfigurationLocation id="8786fc83-e187-44e5-a25c-56ddd57a57d9" type="BUNDLED" scope="All" description="Sun Checks">(bundled)</ConfigurationLocation>
<ConfigurationLocation id="9e21369b-7e23-4481-9f03-a749830b2ca0" type="BUNDLED" scope="All" description="Google Checks">(bundled)</ConfigurationLocation>

I will disable these 2 to see whether it gets back or is modified (as a workaround). But it seems there's still some problems.

**Comment by jshiell** [comment]
Do you see anything harmful happening as a result of it? The bundles configs are handled in a special manner, in particular in regards to ensuring they exist. But the IDs are only temporally valid - as long as they're consistent within a saved file (i.e. with the active config IDs) it shouldn't matter if they change between saves.

**Comment by ladislavlencucha** [comment]
Well, it doesn't break anything, it's just that the ID changes. And as a result, I see tracked file with modification that should be committed (as mentioned, we have the config file in git).

I removed those 2 entries from configuration file and so far it seems the plugin does not attempt to put them back and there are no modification of the file happening.

**Comment by jshiell** [comment]
Ah, excellent point on the Git front - I'll have a look and see if there's anything we can do to make those more stable.

**Comment by LennyKarpel** [comment]
I see this as well (the changing of the ConfigurationLocation "id" attribute) .. for me it is simple to reproduce .. start with no git changes .. change any file .. using IDEA shelve the change .. note that the 'checkstyle-idea.xml' file is now changed with new IDs.

**Comment by ladislavlencucha** [comment]
Yes, it can also by reproduced by committing any file or pulling with rebase when I have a local commit. Seems like the same operation as unshelving.

**Comment by jshiell** [comment]
I can't find any cause for regeneration, but it will generate random IDs in any legacy case where there isn't an ID, which isn't ideal when multiple users are involved. Also, the bundled configs should be restored to the file when removed. My plan is to fix both problems and have bundled configurations use a predefined ID when added/regenerated, so that it should always be constant (although if an ID is present it'll continue using it, to avoid disrupting more config files...).

**Comment by LennyKarpel** [comment]
Hey. My new config file still has an ID for the configuration file I added. Will that ID be stable ??
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA" serialisationVersion="2">
    <checkstyleVersion>10.3</checkstyleVersion>
    <scanScope>JavaOnly</scanScope>
    <option name="thirdPartyClasspath" />
    <option name="activeLocationIds">
      <option value="c212844d-5ab3-4bdd-92b0-13ac5dab852d" />
      <option value="d90ab4fd-705b-485f-9d2f-5e47def4a037" />
    </option>
    <option name="locations">
      <list>
        <ConfigurationLocation id="bundled-sun-checks" type="BUNDLED" scope="All" description="Sun Checks">(bundled)</ConfigurationLocation>
        <ConfigurationLocation id="bundled-google-checks" type="BUNDLED" scope="All" description="Google Checks">(bundled)</ConfigurationLocation>
        <ConfigurationLocation id="d90ab4fd-705b-485f-9d2f-5e47def4a037" type="LOCAL_FILE" scope="All" description="Project Checks">
          $PROJECT_DIR$/config/checkstyle/checkstyle.xml
          <option name="properties">
            <map>
              <entry key="config_loc" value="" />
            </map>
          </option>
        </ConfigurationLocation>
      </list>
    </option>
  </component>
</project>
```

**Comment by jshiell** [comment]
It _should_ - a new ID should only be generated when a) an entry doesn't have one (e.g. importing an old configuration format) or b) when a new entry is added. Otherwise it should remain stable once generated.
